# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/staylor/Projects/PAIRS/GitHub/ei-geospatial-qgis-plugin/0.0.6/ei-geospatial-qgis-plugin-internal/src/ei_geospatial/ibmpairs_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


